def aggiungi(v):
    c = "Copertine e miniature fotografiche rifatte come scene vettoriali (pianeta con luci, persone in silhouette, colonne, sala di un evento, città, sfera luminosa): nessun raster. "
    v(["49.001"], "49-01-splash", "svg", "Il catalogo etichetta 49.001 'foto' ma contiene tre telefoni (splash, onboarding, home): sono 49-01, 49-02, 49-03. Splash blu con logo e slogan, cerchi di fondo tenui.")
    v(["49.001"], "49-02-onboarding", "svg", "Seconda schermata di 49.001: onboarding con logo AddiOfa a due colori; illustrazione dei fogli ridisegnata (nell'originale due fogli con righe sfocate).")
    v(["49.001"], "49-03-home", "svg", "Terza schermata di 49.001: home con 82 % (diversa dalla home di 25 e 03: qui c'è la scheda «Prossimo passo» e «Il tuo percorso»). Misuratore con tacche, grafico con valori allineati, barra di navigazione a 4 voci con indicatore home.")
    v(["49.002"], None, "scartato", "frammento: striscia con l'ora «9:41» della barra di stato; coperta dagli SVG delle schermate.")
    v(["49.003"], None, "scartato", "frammento: strisce di barra di stato di sei schermate; coperta dagli SVG.")
    v(["49.004"], "49-04-lezioni", "svg", "Elenco «Lezioni» (8 voci, 2 completate, «Future tenses» evidenziata). Cerchi numerati e spunte regolarizzati; barra a 4 voci con «Studia» attiva.")
    v(["49.005"], "49-05-esercizio", "svg", "Il riquadro contiene due schermate: esercizio «Completa la frase» (questo SVG, con feedback «Corretto!») e «Simulazioni» (49-06). Risposte allineate alla stessa x.")
    v(["49.005"], "49-06-simulazioni", "svg", "Seconda schermata di 49.005: Simulazioni con tre voci (completa, per argomento, le mie).")
    v(["49.006"], "49-07-profilo", "svg", "Profilo: avatar con iniziale, voci con icone ridisegnate (barre, campana, aiuto, ingranaggio, esci), interruttore notifiche. Nell'originale nessuna voce della barra è attiva: attivato «Profilo».")
    v(["49.007"], None, "scartato", "testo: striscia di didascalie del foglio (titoli 'ATLAS – Conoscenza, strumenti, opportunità', 'NOI', 'Agorà' con logo): non fa parte delle schermate.")
    v(["49.008"], "49-08-esplora", "svg", "Pannello con tre telefoni: Esplora (questo SVG, con tre schede ATLAS/NOI/Agorà), ATLAS home (49-09), ATLAS articolo (49-10). " + c)
    v(["49.008"], "49-09-atlas-home", "svg", "Seconda schermata di 49.008: ATLAS home con chip, copertina scura, «In evidenza» e due articoli. " + c)
    v(["49.008"], "49-10-atlas-articolo", "svg", "Terza schermata di 49.008: articolo ATLAS con copertina a pianeta, chip «Tecnologia», titolo, tempo di lettura. " + c)
    v(["49.009"], "49-11-noi-home", "svg", "Pannello con quattro telefoni: NOI home (questo SVG), evento (49-12), Agorà home (49-13), discussione (49-14). Colore della sezione verde. Avatar disegnati. " + c)
    v(["49.009"], "49-12-noi-evento", "svg", "NOI evento «Aperitivo PoliNetwork» con copertina vettoriale, data/luogo, partecipanti, pulsante «Partecipo». " + c)
    v(["49.009"], "49-13-agora-home", "svg", "Agorà home con chip scorrevoli (l'ultimo «Tecnologia» tagliato dal bordo come nell'originale), copertina «Discussioni» e tre discussioni popolari. Colore della sezione arancio. " + c)
    v(["49.009"], "49-14-agora-discussione", "svg", "Discussione «È giusto che l'università blocchi gli esami per l'OFA?» con scheda «Più rilevanti» e primo commento. Testi leggibili.")
